version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring
    depends_on:
      - python-exporter
      - go-exporter

  python-exporter:
    restart: always
    build:
      context: ../../../day-2/files/primeiro-exporter/final
      dockerfile: Dockerfile
    container_name: python-exporter
    ports:
      - "0.0.0.0:8899:8899"
    networks:
      - monitoring
    environment:
      - PYTHONUNBUFFERED=1

  go-exporter:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-exporter
    ports:
      - "0.0.0.0:7788:7788"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
