global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files: 
  - alertas.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
    
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "python-exporter"
    static_configs:
      - targets: ["python-exporter:8899"]
  
  - job_name: 'go-exporter'
    static_configs:
      - targets: ['go-exporter:7788']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']