services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
      - ./alerts-completo.yaml:/etc/prometheus/alerts-completo.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring
    depends_on:
      - python-exporter
      - go-exporter
      - node-exporter
      - alertmanager

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "0.0.0.0:9093:9093"
    # Carrega as variáveis do arquivo .env para dentro do container
    environment:
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
    volumes:
      # Montamos o template como somente leitura
      - ./alertmanager-discord.template.yaml:/etc/alertmanager/alertmanager.yml:rw
      # (Opcional) Persistência de dados se precisar
      - alertmanager_data:/alertmanager
    
    # Substituição em tempo de execução
    # Usamos o separador '|' no sed porque a URL contém barras '/'
    # Alertmanager é iniciado usando o arquivo do diretorio /tmp/:
    # exec /bin/alertmanager --config.file=/tmp/alertmanager.yml
    entrypoint:
      - /bin/sh
      - -c
      - |
        sed "s|__DISCORD_WEBHOOK_URL__|$DISCORD_WEBHOOK|g" /etc/alertmanager/alertmanager.yml > /tmp/alertmanager.yml && \
        exec /bin/alertmanager --config.file=/tmp/alertmanager.yml --storage.path=/alertmanager
    networks:
      - monitoring

  python-exporter:
    restart: always
    build:
      context: ../../day-2/files/primeiro-exporter/final
      dockerfile: Dockerfile
    container_name: python-exporter
    ports:
      - "0.0.0.0:8899:8899"
    networks:
      - monitoring
    environment:
      - PYTHONUNBUFFERED=1

  go-exporter:
    restart: always
    build:
      context: ../../day-3/files/segundo-exporter
      dockerfile: Dockerfile
    container_name: go-exporter
    ports:
      - "0.0.0.0:7788:7788"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "0.0.0.0:9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.systemd'
    networks:
      - monitoring
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin # giropops
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:

